### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by cprima** [ninethousand/NineThousandJobqueueBundle#1]
In AppKernel.php the line should read
`new NineThousand\Bundle\NineThousandJobqueueBundle\NineThousandJobqueueBundle(),`

I have fos_user installed already and get an Exception:
`php app/console doctrine:schema:update
  [Doctrine\DBAL\Schema\SchemaException]          
  The table with name 'fos_user' already exists.`

**Comment by jessegreathouse** [comment]
Hi, thanks very much for pointing out the error in my documentation for appKernel instructions. I have made an update which corrects the error.

about the fos_user problem, this is the case of an entity attempting to create a table with the same name as your FOSUserBundle:User Entity, however, none of the Entities in this bundle are attempting to use that table name. Check the entities in your project for other entities that are attempting to use the table name fos_user. This is not a problem related to the NineThousandJobqueueBundle.
